package com.cooksys.training.model;

// Generated May 6, 2014 2:21:07 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Customerbackup generated by hbm2java
 */
@Entity
@Table(name = "customerbackup", catalog = "sakila")
public class Customerbackup implements java.io.Serializable {

	private CustomerbackupId id;

	public Customerbackup() {
	}

	public Customerbackup(CustomerbackupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "customer_id", nullable = false)),
			@AttributeOverride(name = "storeId", column = @Column(name = "store_id", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name", nullable = false, length = 45)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name", nullable = false, length = 45)),
			@AttributeOverride(name = "email", column = @Column(name = "email", length = 50)),
			@AttributeOverride(name = "addressId", column = @Column(name = "address_id", nullable = false)),
			@AttributeOverride(name = "active", column = @Column(name = "active", nullable = false)),
			@AttributeOverride(name = "createDate", column = @Column(name = "create_date", nullable = false, length = 19)),
			@AttributeOverride(name = "lastUpdate", column = @Column(name = "last_update", nullable = false, length = 19)) })
	public CustomerbackupId getId() {
		return this.id;
	}

	public void setId(CustomerbackupId id) {
		this.id = id;
	}

}
